defaults:
  model_type: "transformer"  # transformer or resnet
  n_blocks: 5
  n_heads: 4
  n_embed: 256
  dropout: 0.2
  batch_size: 5000
  data_path: "data/v8"
  merge_background: False
  use_weights: False
  seed: 0
  trn_split: 0.8
  epochs: 300
  name: "[big]"

  evaluations:
    - feature_importance
    - roc
    - confusion_matrix
    - significance

variations:
  features:
    # All features
    all:
      - HT
      - HT_fwdJets
      - HT_inclFwdJets
      - HT_lep
      - HT_jets
      - HT_taus

      - jets_eta_0
      - jets_pt_0
      - jets_e_0
      - jets_phi_0

      - jets_eta_1
      - jets_pt_1
      - jets_e_1
      - jets_phi_1

      - jets_eta_2
      - jets_pt_2
      - jets_e_2
      - jets_phi_2

      - jets_eta_3
      - jets_pt_3
      - jets_e_3
      - jets_phi_3

      - jets_eta_4
      - jets_pt_4
      - jets_e_4
      - jets_phi_4

      - jets_eta_5
      - jets_pt_5
      - jets_e_5
      - jets_phi_5

      - lep_E_0
      - lep_E_1
      - lep_Eta_0
      - lep_Eta_1
      - lep_EtaBE2_0
      - lep_EtaBE2_1
      - lep_ID_0
      - lep_ID_1
      - lep_ambiguityType_0
      - lep_ambiguityType_1
      - lep_sigd0PV_0
      - lep_sigd0PV_1
      - Mb1
      - lep_Mtrktrk_atConvV_CO_0
      - lep_Mtrktrk_atConvV_CO_1
      - lep_Mtrktrk_atPV_CO_0
      - lep_Mtrktrk_atPV_CO_1
      - lep_nInnerPix_0
      - lep_nInnerPix_1
      - lep_nTrackParticles_0
      - lep_nTrackParticles_1
      - lep_Phi_0
      - lep_Phi_1
      - lep_Pt_0
      - lep_Pt_1
      - lep_sigd0PV_0
      - lep_sigd0PV_1
      - lep_Z0SinTheta_0
      - lep_Z0SinTheta_1
      - max_eta
      - met_met
      - met_phi
      - taus_DL1r_0
      - taus_charge_0
      - taus_decayMode_0
      - taus_eta_0
      - taus_fromPV_0
      - taus_numTrack_0
      - taus_passEleBDT_0
      - taus_passEleOLR_0
      - taus_passJVT_0
      - taus_phi_0
      - taus_pt_0
      - taus_width_0
      - minDeltaR_LJ_0
      - minDeltaR_LJ_1
      - minDeltaR_LJ_2
      - minOSMll
      - minOSSFMll
      - mjjMax_frwdJet
      - MLepMet
      - Mll01
      - Mlll012
      - Mllll0123
      - MtLepMet
      - nFwdJets_OR
      - nJets_OR
      - nTaus_OR_Pt25
      - Ptll01
      - sumPsbtag
      - total_charge
      - Mlb
      - total_leptons
      - passPLIVTight_0
      - passPLIVTight_1
      - nJets_OR_DL1r_77
      - nTaus_OR
      - best_Z_Mll
      - best_Z_other_Mll
      - best_Z_other_MtLepMet
      - DeltaR_min_lep_jet
      - DeltaR_min_lep_jet_fwd
      - dEta_maxMjj_frwdjet
      - dilep_type
      - DRll01
      - DeltaR_max_lep_bjet77
      - DRjj_lead
      - eta_frwdjet
      - flag_JetCleaning_LooseBad
      - MtLep1Met
  classes:
    all:
      - ttH
      - ttW
      - ttW_EW
      - ttZ
      - ttbar
      - VV
      - tZ
      - WtZ
      - tW
      - threeTop
      - fourTop
      - ggVV
      - VVV
      - VH
      - ttWW
      - tHjb
      - tWH
  cuts:
    none:
      other: discard

  fraction:
    - 0.1
    - 0.2
    - 0.5
    - 0.8
    - 1
