defaults:
  name: "resnet"  # transformer or resnet
  n_blocks: 6
  n_embed: 64

  n_embed_categorical: 8

  dropout: 0.0
  batch_size: 1024

  seed: 0
  trn_split: 0.8

  epochs: 200

  repeat: 1

  use_weights: False
  use_binary: False
  cuts: "apply"


  # evaluations:
  #   - feature_importance
  #   - roc
  #   - confusion_matrix
  #   - significance

# compile: False

tags_include:
  - cuts
  - use_weights
  - use_binary
  - use_embedding
  - use_nan_w
  - fraction

variations:
  use_embedding: [True, False]
  use_nan_w: [True, False]


# variations_complete:
  # - cuts: "discard"


  # - use_nan_w: True
    # use_embedding: False

  # - use_nan_w: True
    # use_embedding: True

  # - use_nan_w: False
    # use_embedding: True