defaults:
  model_type: "transformer"  # transformer or resnet
  # n_blocks: 2 # varied
  n_heads: 4
  # n_embed: 64 # varied
  dropout: 0.0
  batch_size: 10000
  seed: 0
  trn_split: 0.8
  epochs: 150
  name: "transformer"
  cuts: "apply"
  repeat: 3

  # evaluations:
  #   - feature_importance
  #   - roc
  #   - confusion_matrix
  #   - significance

# compile: False

tags_include:
  - model_type
  - cuts
  - use_weights
  - use_binary
  - n_embed
  - n_blocks

variations:
  n_embed: [64, 128]
  n_blocks: [2, 4]
  # use_weights: [True, False]
  use_weights: [True]  # Weights seem to not really help a lot
  # use_binary: [True, False]
  use_binary: [False]  # It looks like it's better to try and distinguish between all the classes