source_base_dir: ~/mtcp/friend_ntuples/output/small/nominal
target_base_dir: ~/mtcp/friend_ntuples/output/friend-test/nominal
model_path: ~/mtcp/friend_ntuples/model.py
trex_config: configs/training.config
region: lep-pt-0
branch_name: probs_ttH
batch_size: 5000
# model: resnets/resnet-8
model: transformers/transformer-5-100-data-5000-batch-20-drop
# files:
#     - mc16a/p4418/600793.root
#     - nominal/mc16e/p5035/504338.root
#     - nominal/mc16e/p4590/700205.root
#     - nominal/mc16e/p4590/700336.root
