trex_config: ./configs/training.config
region: "lep-pt-0"
output_path: "output"
features: ./features/merged.yaml
categorical_features: ./features/categorical.yaml
array_features: ./features/array.yaml
invalid_values: ./features/invalid.yaml
n_jets: 6
samples:
    - ttH
    - ttW
    - ttW_EW
    - ttZ
    - ttbar
    - VV
    - tZ
    - WtZ
    - tW
    - threeTop
    - fourTop
    - ggVV
    - VVV
    - VH
    - WttW
    - tHjb
    - tWH
