defaults:
    model_type: "transformer" # transformer or resnet
    n_blocks: 3
    n_heads: 4
    n_embed: 128
    dropout: 0.0
    batch_size: 15000
    merge_background: False
    use_weights: False
    seed: 0
    fraction: 0.2
    trn_split: 0.8
    epochs: 200
    name: "[big]"
    cuts:
        other: "discard"

    evaluations:
        - feature_importance
        - roc
        - confusion_matrix
        - significance
