defaults:
    model_type: "transformer" # transformer or resnet
    n_blocks: 5
    n_heads: 4
    n_embed: 256
    dropout: 0.2
    batch_size: 3072
    merge_background: False
    use_weights: False
    seed: 0
    trn_split: 0.8
    epochs: 200
    name: "[big]"
    cuts:
        other: "discard"

    evaluations:
        - feature_importance
        - roc
        - confusion_matrix
        - significance
